name: learning_audio
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5

  # Audio Music
  just_audio: ^0.10.2

  # Logo Aplikasi
  flutter_launcher_icons: ^0.14.3

  # Splash Screen
  flutter_native_splash: ^2.4.6

  # Theme Color
  flex_color_scheme: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

# Logo Aplikasi
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_worshipy.png"
  min_sdk_android: 21 
  adaptive_icon_background: "#1C1B1B"



flutter:

  uses-material-design: true

  # Image Assets
  assets:
    - assets/

  # Font Family Assets
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900

# Splash Screen
flutter_native_splash:
  color: "#1C1B1B" 
  image: assets/logo_worshipy_1.png 
  android: true 
  ios: true 
  web: false